







framework:
    secret: "some secret here"
    templating:
        engines: ['twig']

services:
    app.exception_listener:
        class: 'Acme\TrainingBundle\EventListener\ExceptionListener'
        tags:
            - { name: "kernel.event_listener", event: "kernel.exception" }
            - { name: "kernel.event_listener", event: "kernel.view" }

    #app.json_rpc_listener:
    #    class: "Acme\\TrainingBundle\\EventListener\\JsonRpcListener"
    #    tags:
    #        - { name: "kernel.event_listener", event: "kernel.request", priority: 255 }
    #        - { name: "kernel.event_listener", event: "kernel.view" }
    #        - { name: "kernel.event_listener", event: "kernel.exception" }
